---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

install:
  - pip install molecule docker

script:
  - molecule test

# rename project directory to match Galaxy role name
before_script:
  - cd ../
  - mv ansible-role-monitoring-plugins transitiv.monitoring-plugins
  - cd transitiv.monitoring-plugins
