---
- name: Prepare
  hosts: all
  tasks:
    - name: Enable PowerTools repo on CentOS 8
      replace:
        path: /etc/yum.repos.d/CentOS-PowerTools.repo
        regexp: '^enabled=0$'
        replace: enabled=1
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_version.split('.')[0] == '8'
