---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure simple test plugin is installed
      stat:
        path: "{{ monitoring_plugins_custom_directory }}/test-plugin.pl"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure advanced test plugin is installed
      stat:
        path: "{{ monitoring_plugins_custom_directory }}/test-plugin2.pl"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg or
                    result.stat.pw_name != 'nobody' or result.stat.mode != '0750'

    - name: Ensure test plugin executes successfully
      command: "{{ monitoring_plugins_custom_directory }}/test-plugin.pl"
      changed_when: false

    - name: Ensure INI file is installed
      stat:
        path: /etc/monitoring-plugins.ini
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg or
                    result.stat.mode != monitoring_plugins_config_mode

    - name: Ensure contents and mode of INI file are correct
      copy:
        path: files/monitoring-plugins.ini
        dest: /etc/monitoring-plugins.ini
        mode: 0640
      register: result
      check_mode: true
      failed_when: result.changed
