---
name: Release

'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'transitiv.monitoring_plugins'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'transitiv.monitoring_plugins'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-base

      - name: Trigger an import on Ansible Galaxy
        run: >
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          transitiv ansible-role-monitoring-plugins
